service: aws-node-http-api-project
frameworkVersion: "3"

custom:
  defaultStage: dev
  environment: ${file(env.yml):${self:provider.stage}, file(env.yml):default}

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, self:custom.defaultStage}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
      Resource: 
        - ${self:custom.environment.arn}

functions:
  register:
    handler: src/register.registerUser
    events:
      - httpApi:
          path: /auth/register
          method: post
  login:
    handler: src/login.login
    events:
      - httpApi:
          path: /auth/login
          method: post

resources:
  Resources:
    WatchQueue2:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: WatchQueue2
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
          